# branches:
#   only:
#     # - master
#     - travis-ci

matrix:
  include:
    services:
      - docker

    - language: node_js
      node_js:
        - "10"
      before_script:
        - .travis/before_run.sh
      script: docker-compose run node npm run test

    # - os: osx
    #   language: objective-c
    #   osx_image: xcode9.4
    #   env:
    #     - JOB_NAME=IOS
    #   script: .travis/ci.sh

    # - os: linux
    #   language: android
    #   jdk: oraclejdk8
    #   sudo: required
    #   android:
    #     components:
    #       - platform-tools
    #       - tools
    #       - build-tools-26.0.3
    #       - android-21
    #       - android-26
    #       - sys-img-armeabi-v7a-android-21
    #       - extra-android-m2repository
    #       - extra-google-m2repository
    #       - extra-google-google_play_services
    #   env:
    #     - JOB_NAME=ANDROID
    #   script: .travis/ci.sh