matrix:
  include:
    # - language: generic
    #   services:
    #     - docker
    #   before_script:
    #     - travis/backend/build.sh
    #   script:
    #     - travis/backend/test.sh
    - language: android
      jdk: oraclejdk8
      sudo: required
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
      android:
        components:
          - platform-tools
          - tools
          - build-tools-28.0.3
          - android-16
          - android-28
          - sys-img-armeabi-v7a-android-28
          - extra-android-m2repository
          - extra-google-m2repository
          - extra-google-google_play_services
      before_script:
        - travis/frontend/build.sh
      script:
        - travis/frontend/test.sh

branches:
  only:
  - master

notifications:
  email:
    on_success: never
    on_failure: never
