matrix:
  include:
    - language: generic
      services:
        - docker
      before_script:
        - travis/backend/build.sh
      script:
        - travis/backend/test.sh

branches:
  only:
  - master

notifications:
  email:
    on_success: never
    on_failure: never
