version: "3"

services:
  redis:
    container_name: jobtogo_redis
    hostname: jobtogo_redis
    image: redis:5.0.6-buster
    ports:
      - "6379:6379"
    networks:
      jobtogo_net:
        ipv4_address: 171.0.0.5
    logging:
      driver: none

  mongodb:
    container_name: jobtogo_db
    hostname: jobtogo_db
    image: mongo:4.2.0
    ports:
      - "27017:27017"
    volumes: 
      - ./mongodata:/data/db:Z
    networks:
      jobtogo_net:
        ipv4_address: 171.0.0.3
    logging:
      driver: none

  node:
    container_name: jobtogo_backend
    hostname: jobtogo_backend
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    image: "jobtogo_backend"
    command: "npm run dev"
    stdin_open: true
    tty: true
    volumes:
      - .:/jobtogo/backend
      - /jobtogo/backend/node_modules
    ports:
      - "8080:8080"
    networks:
      jobtogo_net:
        ipv4_address: 171.0.0.2
    depends_on:
      - mongodb
      - redis

# volumes:
#   mongodata:
#     driver: local

networks:
  jobtogo_net:
    driver: bridge
    ipam:
      config:
        - subnet: 171.0.0.0/16
