version: "3"

services:

  mongodb:
    container_name: jobtogo_db
    hostname: jobtogo_db
    build:
      context: .
      dockerfile: ./docker/mongodb/Dockerfile
    image: "jobtogo_db"
    volumes: 
      - ./mongodata:/data/db:Z
    networks:
      jobtogo_net:
        ipv4_address: 171.0.0.3

  node:
    container_name: jobtogo_backend
    hostname: jobtogo_backend
    build:
      context: .
      dockerfile: ./docker/node/Dockerfile
    image: "jobtogo_backend"
    command: "npm run dev"
    stdin_open: true
    tty: true
    volumes:
      - .:/jobtogo/backend
      - /jobtogo/backend/node_modules
    ports:
      - "8080:8080"
    networks:
      jobtogo_net:
        ipv4_address: 171.0.0.2
    depends_on:
      - mongodb

networks:
  jobtogo_net:
    driver: bridge
    ipam:
      config:
        - subnet: 171.0.0.0/16
